# Generated by Django 4.2.6 on 2023-11-29 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compradores',
            fields=[
                ('id_comprador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'comprador',
                'verbose_name_plural': 'compradores',
            },
        ),
        migrations.CreateModel(
            name='facturaVenta',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.compradores')),
            ],
        ),
        migrations.CreateModel(
            name='ordenPedido',
            fields=[
                ('id_ordenPedido', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('medioDePago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vendedores',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='retroalimentacion',
            fields=[
                ('id_retroalimentacion', models.IntegerField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.compradores')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='comercio')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoria')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.facturaventa')),
                ('id_ordenPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.ordenpedido')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.vendedores'),
        ),
    ]
