# Generated by Django 4.2.6 on 2023-12-08 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversaciones',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='facturaVenta',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('medioDePago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=70)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='comercio')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='publicaciones',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.productos')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'comprador',
                'verbose_name_plural': 'compradores',
            },
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.facturaventa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.productos')),
            ],
        ),
        migrations.CreateModel(
            name='retroalimentacion',
            fields=[
                ('id_retroalimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.publicaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.usuarios'),
        ),
        migrations.CreateModel(
            name='miembros_conversacion',
            fields=[
                ('id_miembros', models.AutoField(primary_key=True, serialize=False)),
                ('id_conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.conversaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.usuarios'),
        ),
    ]
